require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/article_collections", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ArticleCollection. As you add validations to ArticleCollection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: "Name", key: "domain" }
  end

  let(:invalid_attributes) do
    { name: nil, key: nil }
  end

  describe "GET /index" do
    it "renders a successful response" do
      ArticleCollection.create! valid_attributes
      get article_collections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      article_collection = ArticleCollection.create! valid_attributes
      get article_collection_url(article_collection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_article_collection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      article_collection = ArticleCollection.create! valid_attributes
      get edit_article_collection_url(article_collection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ArticleCollection" do
        expect do
          post article_collections_url, params: { article_collection: valid_attributes }
        end.to change(ArticleCollection, :count).by(1)
      end

      it "redirects to the created article_collection" do
        post article_collections_url, params: { article_collection: valid_attributes }
        expect(response).to redirect_to(article_collection_url(ArticleCollection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ArticleCollection" do
        expect do
          post article_collections_url, params: { article_collection: invalid_attributes }
        end.not_to change(ArticleCollection, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post article_collections_url, params: { article_collection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { name: "New name", key: "domain" }
      end

      it "updates the requested article_collection" do
        article_collection = ArticleCollection.create! valid_attributes
        patch article_collection_url(article_collection), params: { article_collection: new_attributes }
        article_collection.reload
        expect(article_collection.name).to eq("New name")
      end

      it "redirects to the article_collection" do
        article_collection = ArticleCollection.create! valid_attributes
        patch article_collection_url(article_collection), params: { article_collection: new_attributes }
        article_collection.reload
        expect(response).to redirect_to(article_collection_url(article_collection))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        article_collection = ArticleCollection.create! valid_attributes
        patch article_collection_url(article_collection), params: { article_collection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested article_collection" do
      article_collection = ArticleCollection.create! valid_attributes
      expect do
        delete article_collection_url(article_collection)
      end.to change(ArticleCollection, :count).by(-1)
    end

    it "redirects to the article_collections list" do
      article_collection = ArticleCollection.create! valid_attributes
      delete article_collection_url(article_collection)
      expect(response).to redirect_to(article_collections_url)
    end
  end
end
