require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/article_collections", type: :request do
  let(:article) { create(:article, site_name: "Example site", title: "Example article") }
  let(:article_collection) { create(:article_collection, key: "site_name", value: "Example site") }

  # This should return the minimal set of attributes required to create a valid
  # ArticleCollection. As you add validations to ArticleCollection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: "Name", key: "site_name", value: "Value" }
  end

  let(:invalid_attributes) do
    { name: nil, key: nil, value: nil }
  end

  describe "GET /index" do
    it "renders a successful response" do
      ArticleCollection.create! valid_attributes
      get article_collections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      article_collection = ArticleCollection.create! valid_attributes
      get article_collection_url(article_collection)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_article_collection_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      article_collection = ArticleCollection.create! valid_attributes
      get edit_article_collection_url(article_collection)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ArticleCollection" do
        expect do
          post article_collections_url, params: { article_collection: valid_attributes }
        end.to change(ArticleCollection, :count).by(1)
      end

      it "redirects to the created article_collection" do
        post article_collections_url, params: { article_collection: valid_attributes }
        expect(response).to redirect_to(article_collection_url(ArticleCollection.last))
      end

      context "with trubo_stream" do
        it "creates a new ArticleCollection and returns success", :aggregate_failures do
          expect do
            post article_collections_path, params: { article_collection: valid_attributes }, as: :turbo_stream
          end.to change(ArticleCollection, :count).by(1)

          expect(response).to have_http_status(:success)
          expect(response.media_type).to eq "text/vnd.turbo-stream.html"
        end
      end
    end

    context "with invalid parameters" do
      it "does not create a new ArticleCollection" do
        expect do
          post article_collections_url, params: { article_collection: invalid_attributes }
        end.not_to change(ArticleCollection, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post article_collections_url, params: { article_collection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end

      context "with trubo_stream" do
        it "does not ceate a new ArticleCollectioni and returns unprocessable_content", :aggregate_failures do
          expect do
            post article_collections_path, params: { article_collection: invalid_attributes }, as: :turbo_stream
          end.not_to change(ArticleCollection, :count)

          expect(response).to have_http_status(:unprocessable_content)
        end
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { name: "New name", key: "site_name", value: "Value" }
      end

      it "updates the requested article_collection" do
        article_collection = ArticleCollection.create! valid_attributes
        patch article_collection_url(article_collection), params: { article_collection: new_attributes }
        article_collection.reload
        expect(article_collection.name).to eq("New name")
      end

      it "redirects to the article_collection" do
        article_collection = ArticleCollection.create! valid_attributes
        patch article_collection_url(article_collection), params: { article_collection: new_attributes }
        article_collection.reload
        expect(response).to redirect_to(article_collection_url(article_collection))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        article_collection = ArticleCollection.create! valid_attributes
        patch article_collection_url(article_collection), params: { article_collection: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested article_collection" do
      article_collection = ArticleCollection.create! valid_attributes
      expect do
        delete article_collection_url(article_collection)
      end.to change(ArticleCollection, :count).by(-1)
    end

    it "redirects to the article_collections list" do
      article_collection = ArticleCollection.create! valid_attributes
      delete article_collection_url(article_collection)
      expect(response).to redirect_to(article_collections_url)
    end
  end

  describe "GET /article_collections/:id/articles" do
    it "shows articles in the article collection" do
      get articles_article_collection_path(article_collection)
      expect(response).to be_successful
    end

    context "when the article_collection does not exist" do
      it "returns not_found" do
        non_existent_id = article_collection.id
        article_collection.destroy

        get articles_article_collection_path(id: non_existent_id)
        expect(response).to have_http_status(:not_found)
      end
    end
  end
end
