require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/collection_tags", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CollectionTag. As you add validations to CollectionTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: "Name" }
  end

  let(:invalid_attributes) do
    { name: nil }
  end

  describe "GET /index" do
    it "renders a successful response" do
      CollectionTag.create! valid_attributes
      get collection_tags_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      collection_tag = CollectionTag.create! valid_attributes
      get collection_tag_url(collection_tag)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_collection_tag_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      collection_tag = CollectionTag.create! valid_attributes
      get edit_collection_tag_url(collection_tag)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CollectionTag" do
        expect do
          post collection_tags_url, params: { collection_tag: valid_attributes }
        end.to change(CollectionTag, :count).by(1)
      end

      it "redirects to the created collection_tag" do
        post collection_tags_url, params: { collection_tag: valid_attributes }
        expect(response).to redirect_to(collection_tag_url(CollectionTag.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CollectionTag" do
        expect do
          post collection_tags_url, params: { collection_tag: invalid_attributes }
        end.not_to change(CollectionTag, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post collection_tags_url, params: { collection_tag: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { name: "New name" }
      end

      it "updates the requested collection_tag" do
        collection_tag = CollectionTag.create! valid_attributes
        patch collection_tag_url(collection_tag), params: { collection_tag: new_attributes }
        collection_tag.reload
        expect(collection_tag.name).to eq("New name")
      end

      it "redirects to the collection_tag" do
        collection_tag = CollectionTag.create! valid_attributes
        patch collection_tag_url(collection_tag), params: { collection_tag: new_attributes }
        collection_tag.reload
        expect(response).to redirect_to(collection_tag_url(collection_tag))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        collection_tag = CollectionTag.create! valid_attributes
        patch collection_tag_url(collection_tag), params: { collection_tag: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested collection_tag" do
      collection_tag = CollectionTag.create! valid_attributes
      expect do
        delete collection_tag_url(collection_tag)
      end.to change(CollectionTag, :count).by(-1)
    end

    it "redirects to the collection_tags list" do
      collection_tag = CollectionTag.create! valid_attributes
      delete collection_tag_url(collection_tag)
      expect(response).to redirect_to(collection_tags_url)
    end
  end
end
