require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/site_name_corrections", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SiteNameCorrection. As you add validations to SiteNameCorrection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { domain: "example.org", name: "Name" }
  end

  let(:invalid_attributes) do
    { domain: "example.org", name: nil }
  end

  describe "GET /index" do
    it "renders a successful response" do
      SiteNameCorrection.create! valid_attributes
      get site_name_corrections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      site_name_correction = SiteNameCorrection.create! valid_attributes
      get site_name_correction_url(site_name_correction)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_site_name_correction_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      site_name_correction = SiteNameCorrection.create! valid_attributes
      get edit_site_name_correction_url(site_name_correction)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SiteNameCorrection" do
        expect do
          post site_name_corrections_url, params: { site_name_correction: valid_attributes }
        end.to change(SiteNameCorrection, :count).by(1)
      end

      it "redirects to the created site_name_correction" do
        post site_name_corrections_url, params: { site_name_correction: valid_attributes }
        expect(response).to redirect_to(site_name_correction_url(SiteNameCorrection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SiteNameCorrection" do
        expect do
          post site_name_corrections_url, params: { site_name_correction: invalid_attributes }
        end.not_to change(SiteNameCorrection, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post site_name_corrections_url, params: { site_name_correction: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        { domain: "example.org", name: "New name" }
      end

      it "updates the requested site_name_correction" do
        site_name_correction = SiteNameCorrection.create! valid_attributes
        patch site_name_correction_url(site_name_correction), params: { site_name_correction: new_attributes }
        site_name_correction.reload

        expect(site_name_correction.name).to eq("New name")
      end

      it "redirects to the site_name_correction" do
        site_name_correction = SiteNameCorrection.create! valid_attributes
        patch site_name_correction_url(site_name_correction), params: { site_name_correction: new_attributes }
        site_name_correction.reload
        expect(response).to redirect_to(site_name_correction_url(site_name_correction))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        site_name_correction = SiteNameCorrection.create! valid_attributes
        patch site_name_correction_url(site_name_correction), params: { site_name_correction: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested site_name_correction" do
      site_name_correction = SiteNameCorrection.create! valid_attributes
      expect do
        delete site_name_correction_url(site_name_correction)
      end.to change(SiteNameCorrection, :count).by(-1)
    end

    it "redirects to the site_name_corrections list" do
      site_name_correction = SiteNameCorrection.create! valid_attributes
      delete site_name_correction_url(site_name_correction)
      expect(response).to redirect_to(site_name_corrections_url)
    end
  end
end
